### ISSUE TITLE
#__blaze-root div overrides css height property?

### ISSUE THREAD

**Issue by 0xpatrickdev** [kadirahq/blaze-layout#59]
I was working with the [jquery UI Layout](http://layout.jquery-dev.com/) plugin and needed to set the `height` to `100%`.  I was attempting to with `html`, `body`, and `#myContainer`, but didnt realize there was an encapsulating div with the `#__blaze-root` id.  Initially I thought my issue was non-blaze related and had something to do with the load order of the scripts, but eventually realized it was due to `#__blaze-root`.

Is`#__blaze-root` supposed to have css properties?  I have since added it to my stylesheet and do not have an issue, but the documentation doesn't mention anything about this div or the id.

**Comment by arunoda** [comment]
Check this. You can change the root as you want.
See: https://github.com/kadirahq/blaze-layout#set-different-root-node

**Comment by 0xpatrickdev** [comment]
Ah i see. Thank you @arunoda

**Comment by Kamin12** [comment]
I see that you can set CSS properties for _blaze-root. But is there any way to set different blaze root properties for each template?

If I set the _blaze-root property to background-color: green, won't it appear green on all templates? I'm looking for a way to change the properties only for one template.

Also, is there a way to specify BlazeLayout.setroute('body'); to different 'body' like elements for different routes or templates?

Also, there seems to be a body tag automatically generated. Is there a way to change the CSS property of this body tag on one template, but not of them all? I can't properly change the CSS background-color fill because I would need to change this body template's properties, but changing this body template's properties would affect all of them.
